const ProductIdentity = require('../utils/ProductIdentity');
const AIProviderFactory = require('../utils/AIProviderFactory');
const CandidateResolverService = require('./CandidateResolverService');
const ProductMetadataParser = require('../utils/ProductMetadataParser');

class SearchRecoveryService {
  constructor(options = {}) {
    this.aiProvider = options.aiProvider || AIProviderFactory.getProvider(options);
    this.candidateResolver = options.candidateResolver || new CandidateResolverService({ aiProvider: this.aiProvider });
  }

  /**
   * Validates and sanitizes Claude generated search queries.
   * @param {Array<string>} rawQueries
   * @param {Array<string>} previousAttempts
   * @param {Object} productIdentity
   * @returns {Array<string>} Safe, deduplicated queries
   */
  sanitizeQueries(rawQueries = [], previousAttempts = [], productIdentity = {}) {
    if (!Array.isArray(rawQueries)) return [];

    const prevSet = new Set(previousAttempts.map(q => String(q).toLowerCase().trim()));
    const safeQueries = [];

    const forbiddenPatterns = [
      /select /i, /insert /i, /delete /i, /drop /i, /<script/i, /javascript:/i,
      /http:\/\//i, /https:\/\//i, /bearer/i, /token/i, /password/i, /cookie/i,
      /api_key/i, /\.php/i, /\.html/i, /auth/i
    ];

    const catBrand = (productIdentity.brand || '').toLowerCase();

    for (const raw of rawQueries) {
      if (typeof raw !== 'string') continue;
      const clean = raw.trim();

      if (!clean || clean.length < 2 || clean.length > 80) continue;

      const containsForbidden = forbiddenPatterns.some(pattern => pattern.test(clean));
      if (containsForbidden) continue;

      const cleanLower = clean.toLowerCase();
      if (prevSet.has(cleanLower)) continue;

      // Reject brand-changing queries if catalogue brand is known and clean query contains a different brand
      if (catBrand && catBrand.length > 2) {
        const queryBrand = ProductMetadataParser.extractBrand(clean);
        if (queryBrand && queryBrand.toLowerCase() !== catBrand) {
          // Skip queries that hallucinate a completely different brand
          continue;
        }
      }

      prevSet.add(cleanLower);
      safeQueries.push(clean);

      if (safeQueries.length >= 3) break;
    }

    return safeQueries;
  }

  /**
   * Executes AI-assisted search recovery for a NOT_FOUND catalogue item.
   * @param {Object} catItem - Catalogue product item
   * @param {string} supplierName - Name of wholesaler (e.g. 'booker', 'bestway', 'parfetts', 'costco')
   * @param {Object} options - Search execution options
   * @returns {Promise<Object>} Recovery result
   */
  async recoverNotFoundItem(catItem, supplierName, options = {}) {
    const startTime = Date.now();
    const productIdentity = new ProductIdentity({
      catalogueItemId: catItem.id,
      ean: catItem.barcode,
      rawTitle: catItem.name || catItem.product_name
    });

    const previousAttempts = Array.isArray(options.previousAttempts) ? options.previousAttempts : [catItem.barcode, catItem.name].filter(Boolean);

    let searchRecoveryCalled = false;
    let rawQueries = [];

    // STEP 1: Generate AI Search Queries if AI provider configured
    if (!this.aiProvider || !this.aiProvider.isConfigured()) {
      return {
        finalStatus: 'AI_RECOVERY_UNAVAILABLE',
        searchRecoveryCalled: false,
        generatedQueries: [],
        queryAttempts: [],
        candidateResolverCalled: false,
        recommendedCandidate: null,
        reasoningSummary: 'AI provider missing or unconfigured in environment.',
        latencyMs: Date.now() - startTime
      };
    }

    searchRecoveryCalled = true;
    const aiQueryResult = await this.aiProvider.generateSearchQueries(productIdentity, supplierName);
    rawQueries = aiQueryResult.queries || [];

    const safeQueries = this.sanitizeQueries(rawQueries, previousAttempts, productIdentity);

    if (safeQueries.length === 0) {
      return {
        finalStatus: 'SEARCH_STRATEGY_EXHAUSTED',
        searchRecoveryCalled,
        generatedQueries: [],
        queryAttempts: [],
        candidateResolverCalled: false,
        recommendedCandidate: null,
        reasoningSummary: 'No new valid search queries generated by AI.',
        latencyMs: Date.now() - startTime
      };
    }

    const queryAttempts = [];
    let winningResult = null;

    // STEP 2: Execute search queries sequentially
    for (const query of safeQueries) {
      let realCandidates = [];
      let supplierExecuted = false;
      let searchStatus = 'SEARCH_OK_ZERO_RESULTS';

      if (typeof options.searchFn === 'function') {
        supplierExecuted = true;
        try {
          const res = await options.searchFn(query, supplierName);
          if (Array.isArray(res)) {
            realCandidates = res;
            searchStatus = realCandidates.length > 0 ? 'SEARCH_OK_RESULTS' : 'SEARCH_OK_ZERO_RESULTS';
          } else if (res && typeof res === 'object') {
            realCandidates = Array.isArray(res.candidates) ? res.candidates : [];
            searchStatus = res.status || (realCandidates.length > 0 ? 'SEARCH_OK_RESULTS' : 'SEARCH_OK_ZERO_RESULTS');
          }
        } catch (err) {
          realCandidates = [];
          searchStatus = err.message.includes('AUTH') ? 'AUTH_FAILURE' :
                         err.message.includes('TIMEOUT') ? 'TIMEOUT' :
                         err.message.includes('PARSER') ? 'PARSER_FAILURE' : 'NETWORK_FAILURE';
        }
      }

      queryAttempts.push({
        query,
        supplierExecuted,
        searchStatus,
        resultCount: realCandidates.length,
        viableCount: 0
      });

      if (searchStatus !== 'SEARCH_OK_RESULTS' || realCandidates.length === 0) continue;

      // STEP 3: Deterministic Candidate Elimination
      const viableCandidates = [];
      for (const cand of realCandidates) {
        const evalRes = this.candidateResolver.evaluateCandidateDeterministic(catItem, cand);
        if (evalRes.result_status !== 'rejected') {
          viableCandidates.push({ candidate: cand, eval: evalRes });
        }
      }

      queryAttempts[queryAttempts.length - 1].viableCount = viableCandidates.length;

      if (viableCandidates.length === 0) continue;

      // Branch A: Exactly 1 viable candidate passing with score >= 90
      if (viableCandidates.length === 1 && viableCandidates[0].eval.validation_score >= 90) {
        const selected = viableCandidates[0].candidate;
        winningResult = {
          finalStatus: 'VERIFIED_EQUIVALENT',
          searchRecoveryCalled,
          generatedQueries: safeQueries,
          queryAttempts,
          candidateResolverCalled: false,
          recommendedCandidate: selected,
          aiConfidence: 1.0,
          hardValidatorResult: 'PASS_DETERMINISTIC',
          reasoningSummary: `Recovered single valid candidate via query "${query}" without calling candidate resolver AI.`,
          latencyMs: Date.now() - startTime
        };
        break;
      }

      // Branch B: 2+ viable candidates OR 1 candidate with score < 90 -> Invoke CandidateResolverService
      const candidateObjects = viableCandidates.map(v => v.candidate);
      const resolveRes = await this.candidateResolver.resolveAmbiguous(catItem, candidateObjects);

      if (resolveRes.finalStatus === 'VERIFIED_EQUIVALENT') {
        winningResult = {
          finalStatus: 'VERIFIED_EQUIVALENT',
          searchRecoveryCalled,
          generatedQueries: safeQueries,
          queryAttempts,
          candidateResolverCalled: resolveRes.aiCalled,
          recommendedCandidate: resolveRes.recommendedCandidate,
          aiConfidence: resolveRes.aiConfidence,
          hardValidatorResult: resolveRes.hardValidatorResult,
          reasoningSummary: `Recovered match via query "${query}": ${resolveRes.reasoningSummary}`,
          latencyMs: Date.now() - startTime
        };
        break;
      } else if (resolveRes.finalStatus === 'NEEDS_REVIEW') {
        winningResult = {
          finalStatus: 'NEEDS_REVIEW',
          searchRecoveryCalled,
          generatedQueries: safeQueries,
          queryAttempts,
          candidateResolverCalled: resolveRes.aiCalled,
          recommendedCandidate: resolveRes.recommendedCandidate,
          aiConfidence: resolveRes.aiConfidence,
          hardValidatorResult: resolveRes.hardValidatorResult,
          reasoningSummary: `Candidate recovered via query "${query}" requires review: ${resolveRes.reasoningSummary}`,
          latencyMs: Date.now() - startTime
        };
      }
    }

    if (winningResult) {
      return winningResult;
    }

    return {
      finalStatus: 'SEARCH_STRATEGY_EXHAUSTED',
      searchRecoveryCalled,
      generatedQueries: safeQueries,
      queryAttempts,
      candidateResolverCalled: false,
      recommendedCandidate: null,
      aiConfidence: 0,
      hardValidatorResult: 'EXHAUSTED_NO_SAFE_MATCH',
      reasoningSummary: `All ${safeQueries.length} recovery queries executed without finding a publishable match.`,
      latencyMs: Date.now() - startTime
    };
  }
}

module.exports = SearchRecoveryService;
